version: '3.8'

services:
  app:
    image: ghcr.io/remla23-team5/app:0.1.2
    ports:
      - "8000:8000"
    environment:
      model_service_url: "http://localhost:8080/predict"
      
  model-service:
    image: ghcr.io/remla23-team5/model-service:main
    ports:
      - "8080:8080"