version: '3.8'

services:
  app:
    image: ghcr.io/remla23-team5/app:latest
    ports:
      - "${APP_PORT:-8000}:8000"
    depends_on:
      - model-service
    environment:
      model_service_url: "http://model-service:8080/predict"

  model-service:
    image: ghcr.io/remla23-team5/model-service:latest
    ports:
      - "8080:8080"
