{
 "title": "Project",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Reviews",
   "type": "stat",
   "description": "This counter metric depicts the number of received reviews.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_reviews", "legendFormat": "Reviews" }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "num_evaluations_per_sentiment{sentiment=\"Unsuccessful\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feedbacks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_feedbacks", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reviews per minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "increase(num_reviews[1m])", "legendFormat": "Reviews" }
   ]
  },
  {
   "title": "Model accuracy",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_accuracy", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Reviews of length",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "reviews_of_length_bucket", "legendFormat": "{{lt}}" }
   ]
  },
  {
   "title": "Evaluations per sentiment",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "num_evaluations_per_sentiment{sentiment!=\"Unsuccessful\"}",
     "legendFormat": "{{sentiment}}"
    }
   ]
  },
  {
   "title": "Evaluations per type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_evaluations_per_type", "legendFormat": "{{type}}" }
   ]
  }
 ]
}