apiVersion: v1
kind: Service
{{- with .Values.services.modelservice }}
metadata:
  name: {{ .name }}
spec:
  selector:
    app: {{ $.Values.deployments.modelservice.selectorLabel }}
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}

---

apiVersion: v1
kind: Service
{{- with .Values.services.app }}
metadata:
  name: {{ .name }}
  labels:
    app: app
spec:
  selector:
    app: {{ $.Values.deployments.app.selectorLabel }}
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .targetPort }}
{{- end }}
