apiVersion: v1
kind: Service
metadata:
  name: model-service-serv
spec:
  selector:
    app: model-service
  ports:
    - port: 8080
      targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: app-serv
  labels:
    app: app-serv
spec:
  selector:
    app: app
  ports:
    - port: 8000
      targetPort: 8000
