apiVersion: v1
kind: Service
metadata:
  name: model-service-serv
spec:
  selector:
    app: {{.Values.modelservice.labelApp}}
  ports:
    - port: {{.Values.modelserviceserv.port}}
      targetPort: {{.Values.modelservice.containerPort}}
---

apiVersion: v1
kind: Service
metadata:
  name: app-serv
  labels:
    app: {{.Values.app.labelApp}}
spec:
  selector:
    app: {{.Values.app.labelApp}}
  ports:
    - port: {{.Values.appserv.port}}
      targetPort: {{.Values.app.containerPort}}
