service:
  app:
    serviceName: app
    ports:
      name: http
      port: 1234
  modelservice:
    serviceName: model-service-serv
    ports:
      name: http
      port: 1234
  mysqldb:
    name: mysqldb-serv
    ports:
      name: http
      port: 3306
    clusterIP: None

deployment:
  app:
    name: app
    labelApp: app
    replicas: 1
    image: ghcr.io/remla23-team5/app
    imageTag: latest
    ports:
      containerPort: 8000
    path: predict
  modelservice:
    labelApp: model-service
    replicas: 1
    image: ghcr.io/remla23-team5/model-service
    imageTag: latest
    ports:
      containerPort: 8080

statefulset:
  mysqldb:
    labelApp: mysqldb
    replicas: 1
    labelApp: mysqldb
    image: mysql
    imageTag: 8.0.30
    ports:
      name: tcp
      protocol: TCP
      containerPort: 3306
    databaseName: restaurants
    storage: 1Gi

hpa:
  app:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  modelservice:
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

serviceMonitor:
  interval: 15s
