apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: app-destination-rule
spec:
  host: {{.Values.service.app.serviceName}}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: model-service-destination-rule
spec:
  host: {{.Values.service.modelservice.serviceName}}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2