apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: limit-app-service-local
spec:
  workloadSelector:
    labels:
      app: app
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: 10
                tokens_per_fill: 10
                fill_interval: 1s
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: false
                  header:
                    key: x-local-rate-limit
                    value: 'true'

---

#{{- $root := . -}}
#{{- with .Values.envoyfilter}}
#apiVersion: networking.istio.io/v1alpha3
#kind: EnvoyFilter
#metadata:
#  name: limit-app-service-local
#spec:
#  workloadSelector:
#    labels:
#      app: {{$root.Values.deployment.appv1.labelApp}}
#  configPatches:
#    - applyTo: HTTP_FILTER
#      match:
#        context: SIDECAR_INBOUND
#        listener:
#          filterChain:
#            filter:
#              name: "envoy.filters.network.http_connection_manager"
#      patch:
#        operation: INSERT_BEFORE
#        value:
#          name: envoy.filters.http.local_ratelimit
#          typed_config:
#            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
#            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
#            value:
#              stat_prefix: http_local_rate_limiter
#              token_bucket:
#                max_tokens: {{.maxTokens}}
#                tokens_per_fill: {{.tokensPerFill}}
#                fill_interval: {{.fillInterval}}
#              filter_enabled:
#                runtime_key: local_rate_limit_enabled
#                default_value:
#                  numerator: 100
#                  denominator: HUNDRED
#              filter_enforced:
#                runtime_key: local_rate_limit_enforced
#                default_value:
#                  numerator: 100
#                  denominator: HUNDRED
#              response_headers_to_add:
#                - append: false
#                  header:
#                    key: x-local-rate-limit
#                    value: 'true'
#{{- end}}