{{- $root := . -}}
{{- with .Values.deployment.modelservice}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service
  labels:
    app: {{.labelApp}}
spec:
  replicas: {{.replicas}}
  selector:
    matchLabels:
      app: {{.labelApp}}
  template:
    metadata:
      labels:
        app: {{.labelApp}}
    spec:
      containers:
      - name: model-service
        image: {{.image}}:{{.imageTag}}
        ports:
        - containerPort: {{.ports.containerPort}}
{{- end}}

---

{{- with .Values.deployment.app}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
  labels:
    app: {{.labelApp}}
spec:
  replicas: {{.replicas}}
  selector:
    matchLabels:
      app: {{.labelApp}}
  template:
    metadata:
      labels:
        app: {{.labelApp}}
    spec:
      containers:
      - name: app
        image: {{.image}}:{{.imageTag}}
        ports:
        - containerPort: {{.ports.containerPort}}
        env:
        - name: model_service_url
          value: http://{{$root.Values.service.modelservice.serviceName}}:{{$root.Values.service.modelservice.ports.port}}/{{.path}}
{{- end}}
